mod postgres './justfiles/postgres.just'
mod prisma './justfiles/prisma.just'

default:
    @just --list

# Set-up local dev
set-up-local-dev:
    @just postgres::start
    @sleep 1
    @bun seed/seed.ts
    @bun run dev
